### ISSUE TITLE
Lines starting with black text turn to purple in other plugins

### ISSUE THREAD

**Issue by SiuanSong** [JustBru00/RenamePlugin#124]
Lines that start with black text lored via EpicRename get returned as default purple italics in other plugins.
Similarly, names that start with white text get returned as blue italics in some plugins.

For example, the line "Collection*" was made using &0.  Upon being returned by a CMI kit, it changes to purple.  This also happens upon a restart with Shopkeepers.
![javaw_SxM5A6yBOj](https://user-images.githubusercontent.com/28202890/70007086-1ce24280-153d-11ea-96de-272bdf152ad5.png)

https://dev.bukkit.org/projects/shopkeepers
https://www.spigotmc.org/resources/cmi-270-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/

**Comment by JustBru00** [comment]
I will need to investigate. Sounds like an incompatibility with these plugins, although that may not be the case. What is the output of the /version command?

**Comment by JustBru00** [comment]
TESTED ON: This server is running CraftBukkit version git-Spigot-56f8471-56118c6 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT

Possibly due to ItemStack serialization as YAML. Will remove &o color code from the beginning of text.
![image](https://user-images.githubusercontent.com/11063799/70108384-35bf2680-1617-11ea-863f-7d83edcb22f3.png)
![image](https://user-images.githubusercontent.com/11063799/70108401-3c4d9e00-1617-11ea-8136-9ada935bc4bc.png)
Tested with Shopkeepers version 2.8.1

**Comment by JustBru00** [comment]
Appears to remove &0 color code from the beginning of any line.
Doesn't happen with white &f color code.

**Comment by JustBru00** [comment]
Found a solution. This is caused by a spigot bug. (https://hub.spigotmc.org/jira/browse/SPIGOT-4441)

This is described by @blablubbabc in Shopkeepers/Shopkeepers#617.
The bug has to do with how spigot handles color codes and converting between minecraft json style text and the color codes that plugins use.

This can be worked around by placing another color code in front of the color code that is deleted.
So to prevent your problem in the image above use `&f&0Collection*` as the lore text and it should be saved and loaded correctly.

![image](https://user-images.githubusercontent.com/11063799/70109504-17a6f580-161a-11ea-98cf-e612fa3d9881.png)


Let me know if this doesn't solve your issue. I will be marking this issue as closed because this is an issue with spigot and not with EpicRename.

- JustBru00

**Comment by SiuanSong** [comment]
Oh wow thats really interesting to know!  Thanks a lot for the info!

**Comment by JustBru00** [comment]
This issue has been fixed upstream.

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/cfeef75cd979c5d2b408645909325a055376c520

https://hub.spigotmc.org/jira/browse/SPIGOT-5749
