### ISSUE TITLE
/removelore Doesn't work

### ISSUE THREAD

**Issue by GeoBay99** [JustBru00/RenamePlugin#172]
Hello.

I've added this plugin to the server and adding permissions accordingly.

Everything seems to be working all smoothly apart from the /removelore command. It says that I do not have permission for that material yet I have * perms.

Please can you advise?

**Comment by JustBru00** [comment]
![image](https://user-images.githubusercontent.com/11063799/209033674-78cd7bbd-15ab-4ea1-96ed-3a935d1a787f.png)
![image](https://user-images.githubusercontent.com/11063799/209033687-9055c60d-89b5-4679-96bc-affc5c528f64.png)

Just tested `epicrename.removelore.*`. The permission doesn't work just as reported.
This issue will be fixed in the next minor update.
