### ISSUE TITLE
Add support for ItemsAdder animated rainbow effect in item renames and item lore if possible

### ISSUE THREAD

**Issue by JustBru00** [JustBru00/RenamePlugin#173]
Requested by `@powerdev` on spigotmc.org. (@alexanderdidio on github.com)

Currently waiting on API implementation from ItemsAdder before starting on this issue.
PluginBugs/Issues-ItemsAdder#2256

![image](https://user-images.githubusercontent.com/11063799/211797636-f3d831f9-c7ae-4ca3-9b8a-61027bcf3c30.png)

**Comment by LoneDev6** [comment]
`/iarename` already supports these effects so you can use it instead.

Sadly there is no easy way to implement an API for that because it uses the Components which are shaded into LoneLibs and you wouldn't be able to access them correctly as it has a different package.

Another thing you can do is read the updated guide in my wiki to use the text effects if you don't have access to "json" components.
https://itemsadder.devs.beer/plugin-usage/text-effects-1.17+#using-them-in-plugins-which-support-legacy-hex-notation

I think you can close this issue and add this information to your plugin wiki too.

**Comment by JustBru00** [comment]
As per comment above users of both EpicRename and ItemsAdder can use &x&F&F&F&F&F&ETest to use the effect.

See https://itemsadder.devs.beer/plugin-usage/text-effects-1.17+#using-them-in-plugins-which-support-legacy-hex-notation
to use other ItemsAdder formatting options.
